import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Header from "./Components/Header";
//Import our Clerk Provider
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from "@clerk/themes";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  //Wrapped my whole app with clerk provider
  return (
    <ClerkProvider
      appearance={{
        baseTheme: [neobrutalism],
        variables: {
          colorPrimary: "#FF4081",
          colorBackground: "#afffff",
        },

        signIn: {
          baseTheme: neobrutalism,
          variables: {
            colorPrimary: "#FF4081",
          },
        },
      }}
    >
      <html lang="en">
        <body
          className={`mt-12 text-center ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
